 # Creation of Array

In [1]:
# Exp5

In [2]:
# Aim - Creation of Array (1D,2D and Multidimennsional array) using numpy

In [ ]:
# Name: Huzaif Khan
# Roll no: 23
# Section: B
# Subject: ET-I

In [4]:
import numpy as np

In [5]:
arr=np.array([50,62,80,26,47,19])

In [6]:
arr

array([50, 62, 80, 26, 47, 19])

In [7]:
arr2=np.array([[50,62,80,26,47,19],[40,56,20,41,38,77]])

In [8]:
arr2

array([[50, 62, 80, 26, 47, 19],
       [40, 56, 20, 41, 38, 77]])

In [9]:
arr3=np.array([[50,62,80,26,47,19],[40,56,20,41,38,77],[10,45,91,54,27,38]])

In [10]:
arr3

array([[50, 62, 80, 26, 47, 19],
       [40, 56, 20, 41, 38, 77],
       [10, 45, 91, 54, 27, 38]])